### ISSUE TITLE
Rely on CSS var for color overrides in base components

### ISSUE THREAD

**Issue by rijkvanzanten** [directus/app-next#14]
Right now, we have a couple base components that rely on properties to override color values, for example:

```vue
<template>
  <div class="my-component">
    <v-button color="red" hover-color="blue">Click me!</v-button>
  </div>
</template>

<style>
.my-component {
  display: flex;
}
</style>
```

We could consider relying on CSS variables to override specific styling elements like this instead:

```vue
<template>
  <div class="my-component">
    <v-button>Click me!</v-button>
  </div>
</template>

<style lang="scss">
.my-component {
  display: flex;

  --v-button-color: red;
  --v-button-hover-color: blue;
}
</style>
```

A big perk of this is that it keeps the separation of concerns pretty strongly, while giving the flexibility over "internal" variables you need. The downside is that it's not very widely used anywhere yet, as this is all pretty newly supported tech (most frameworks etc still rely on Sass variables instead of CSS vars)

**Comment by Nitwel** [comment]
Sounds good. 👍
And it should only be used `when you want to manipulate something directly, which can't cause any side effects.`

For Example:
- colors should be changed via css vars with the tag infront of it like so `--v-component-color` or `--v-component-background-color`.
- text styling could also be changed via css vars.
- position or display should only be changeable using props.
