### ISSUE TITLE
Progress (circular)

### ISSUE THREAD

**Issue by rijkvanzanten** [directus/app-next#16]
Ring that fills up based on progress value. Similar to the linear progress.. but circular

**Comment by Nitwel** [comment]
What about making this a prop of the linear progress bar?

**Comment by rijkvanzanten** [comment]
That could totally work too. The only thing I'm wondering about is when to split components in that case. The circular one will have totally different markup from the linear one, with very different CSS too, making it basically a separate component with the same props 🤔

**Comment by Nitwel** [comment]
The linear and round progress bar will share most of the code so it makes sense to put them together even tho they are different in structure.

**Comment by rijkvanzanten** [comment]
That's also true. We could also considering extracting the logic into a mixin of sorts and re-using it in both components 🤔 

(Not saying that's the right answer, just exploring our options here :) )
