### ISSUE TITLE
Figure out global color palette

### ISSUE THREAD

**Issue by rijkvanzanten** [directus/app-next#29]
Currently, the `_variables.scss` file has a lot of usage / component specific colors that can be made more ambiguous to be reused. 

For example, the v-checkbox is using popover text and input borders kinda hacky:

https://github.com/directus/app-next/blob/0b1f73fc8ed52c8cde4f50c8a74aa33e99ed4981/src/components/v-checkbox/v-checkbox.vue#L114-L124

A good first step would be to have a default set of disabled colors, that can be re-used in the other components.

**Comment by rijkvanzanten** [comment]
Some things that are used often out of the top of my head:

text on page background
text on "sheet" or highlighted section
disabled background
disabled border
text on disabled background
disabled text on page background (f.e. checkbox label)
interface border-color

**Comment by benhaynes** [comment]
## Format
`[scope]-[property]-[state]-[alt]`

## Explanations
* Scope: (eg: `global`, `input`, `button-primary`, `button-secondary`, `module`, `card`)
* Property: (eg: `background-color`, `foreground-color`, `border-width`, etc)
* State: (eg: `hover`, `focus`, `active`, `disabled`)
* Alt: The background color context to use as an override

## Examples
* `global-background-color`
* `global-foreground-color`
* `input-background-color-hover`
* `input-background-color-active`
* `input-background-color-active`
* `button-primary-background-color-disabled`

## Globals
* `highlight`
* `action`
* `success` (with light/dark)
* `warning` (with light/dark)
* `danger` (with light/dark)
