### ISSUE TITLE
Add search-filter functionality

### ISSUE THREAD

**Issue by rijkvanzanten** [directus/app-next#337]
<img width="357" alt="image" src="https://user-images.githubusercontent.com/9141017/78673729-8a69fb00-78b0-11ea-8f1c-5648a9e1a1d3.png">

Either in the sidebar, or in the header. Lets confirm that before implementing.

**Comment by benhaynes** [comment]
I'm torn on the placement here. But the internals will be the exact same (not sure if that matters much). There's less width in the sidebar, and it might be a bit harder to find (not within search). Let's discuss...

Also, in that design mock, the "three dots" was just an experiment, there would only be the "X" (on hover).
