### ISSUE TITLE
Enable soft delete

### ISSUE THREAD

**Issue by rijkvanzanten** [directus/app-next#344]
Make sure to use a slightly different icon. Would be nice if admins have a way to still see the soft deleted items, but that requires an API change

**Comment by benhaynes** [comment]
I've added different icons for soft-delete, hard-delete, and restore. The first two are based on status, for restore, I think all Admins should be able to see soft-deleted items... and the "delete" button on Item Detail becomes "Restore".

Admins having both soft-deleted and non-deleted items on the same listing page might have issues... such as if both are selected, what does the delete button show? So maybe we want to have a "trash" in settings that let's admins restore items from there?

![Screen Shot 2020-04-07 at 11 39 49 AM](https://user-images.githubusercontent.com/522079/78689613-8647d880-78c4-11ea-8332-1271b18a9afc.png)

**Comment by rijkvanzanten** [comment]
> I think all Admins should be able to see soft-deleted items... and the "delete" button on Item Detail becomes "Restore".

I think admins should have both hard-delete and restore in that case. There are instances (esp when using an _unique_ field) when you'd want to go into the trash and permanently delete certain items.

> Admins having both soft-deleted and non-deleted items on the same listing page might have issues... such as if both are selected, what does the delete button show? 

We either have to show both, and disable one/both based on selection, or like you said, have a "trash" collection somewhere in admin only

**Comment by benhaynes** [comment]
Good point — for collections with soft-delete, let's definitely include both *restore* and *hard-delete* as admin options.

Do you have a preference between deleted items in the normal collections area, vs having a dedicated "trash" section in Settings?

**Comment by rijkvanzanten** [comment]
I think I'd personally prefer having them in the same list, and rely on the status display to differentiate between them 🤔 

Also, lets make `restore` the "warning" color instead of the "danger", as it's a non-destructive operation and more of a "good" thing than a "bad" thing (you know what i mean)

**Comment by benhaynes** [comment]
Ok, in that case, let's:

1. Have viewing soft-deleted items set to "off" by default on all browse item page filters.
2. Have the delete button always set to soft-delete (when available) when any item(s) are selected on the item browse page.
3. Have the _orange_ restore button only on item detail. (Admins Only)
4. Include a red _delete permanently_ button only in item detail. (Admins Only) Down to discuss this also being on the browse page for admins.

**Comment by rijkvanzanten** [comment]
> Have viewing soft-deleted items set to "off" by default on all browse item page filters.

How would you toggle it on/off? Have a toggle button with an eye? 👁

**Comment by benhaynes** [comment]
I was thinking it's in the existing filters, but having a default filter might be weird. So yes, a more explicit toggle for soft-deleted items makes more sense. The next question: should that toggle between soft-deleted and everything else, or should there be an option to see everything at once? The former might avoid some of those weird issues we were talking about.

As for where, I think either an Action button in the header, or the sidebar (since it's less used) works.

**Comment by rijkvanzanten** [comment]
I think it should be the difference between hiding the soft-deleted rows and showing them, eg showing them in the middle of all other things. That way, you still have the ability to visually compare the "new" existing items vs the soft deleted ones (eg make sure you don't end up with two Ben Hayness when you restore the soft-deleted item)

**Comment by benhaynes** [comment]
Here's an initial idea for a sidebar toggle.

![Screen Shot 2020-04-09 at 6 39 51 PM](https://user-images.githubusercontent.com/522079/78946728-86e19a00-7a91-11ea-9c49-8d83e8669e1a.png)

Though I think it'd be nice to have the option to see ONLY soft-deleted (like a real "trash"). So maybe this becomes a dropdown with three options:
* Don't Include Soft-Deleted Items
* Include Soft-Deleted Items
* Only Show Soft-Deleted Items 

![Screen Shot 2020-04-09 at 6 43 59 PM](https://user-images.githubusercontent.com/522079/78946976-2010b080-7a92-11ea-8471-c78445ec1182.png)
