### ISSUE TITLE
Add collection-level display template

### ISSUE THREAD

**Issue by rijkvanzanten** [directus/app-next#48]
This would provide a default display template for every interface that uses such an option. It can also be used in the header of the item edit page. Where it currently says "Editing item 15", we could have it render "Editing Getting started. (15)".

@benhaynes any other thoughts / uses that we should consider in this?

**Comment by benhaynes** [comment]
Love it. Yeah, I think this would be setup on the Settings>Collections>Detail page as a field template, eg: `{{first_name}} {{last_name}}`

The component would be one place to adjust fallbacks too.

Would it make sense to cache these titles somehow? Especially if we want to allow any relational data in there, it might be helpful to not look things up each time. 

Also, do we want to allow relational data at all or only use parent fields? The big reason I think relational is important would be Translations... so the title could be based on a specific translation field's locale. This adds a lot of power, but also complexity.

I guess we could start with an MVP and then extend later... at least it will all be consolidated in one component.

**Comment by rijkvanzanten** [comment]
> Would it make sense to cache these titles somehow? Especially if we want to allow any relational data in there, it might be helpful to not look things up each time.

I was thinking about this before in combination with sorting on the item browse pages. Right now, there's no way to sort on the output of this display template (outside of in JS on small datasets).

**Comment by benhaynes** [comment]
Cache options:
* Virtual column on the parent collection
* Actual field on the parent collection, similar to "slug"
* `directus_cache` collection with KVPs (and that collection can be fetched/cached on client side?). Could be useful for other cached data as well.
