### ISSUE TITLE
Dialog / modal

### ISSUE THREAD

**Issue by rijkvanzanten** [directus/app-next#5]
Default modal container. Will often be used in conjunction with tabs.

Should support two "main" styles:

<img width="683" alt="image" src="https://user-images.githubusercontent.com/9141017/74370948-f5fa8500-4da5-11ea-9dd6-ce48ea3259b7.png">

and 

<img width="786" alt="image" src="https://user-images.githubusercontent.com/9141017/74370960-f98e0c00-4da5-11ea-8903-2536d48d1f37.png">

The difference being that no1 doesn't have a header / footer

**Comment by rijkvanzanten** [comment]
We should have v-card first, so we can use the `v-card` as default box for the modal dialog

**Comment by jacobrienstra** [comment]
We should also make sure that if we don't have a header, or actually even if we do, we provide a close button no matter what. Whether an X on top or a button on bottom

**Comment by rijkvanzanten** [comment]
Clicking on the overlay should also close, as should pressing `esc`.

We should only render the `X` if the "force an action" prop is not set. (there are modals where an action is required)

**Comment by rijkvanzanten** [comment]
Implemented in #274
