### ISSUE TITLE
dropdown

### ISSUE THREAD

**Issue by rijkvanzanten** [directus/app-next#60]
https://github.com/directus/app/blob/master/src/interfaces/dropdown/meta.json

**Comment by benhaynes** [comment]
## Options
* `options` — JSON, allow for:
    * Name: The name displayed in the dropdown for each option
    * Value: The value saved to the database for each option
    * Icon: (optional) The icon to display next to the name for each option
    * Group: (optional) Grouping the options should add dividers, not sure if we want to _label_ the groups, probably limit this to only one level deep
    * Color: (optional) Could add individual colors to each option. 
        * Need to decide if this would be applied to the foreground (text and/or icon) or the background (hover selection). If the latter, do we need to include a foreground color option as well? Or would we assume white?
        * Also need to decide if the color would be for the icon, text, or both
* `placeholder` Required, but comes with a default... or optional and the code has a fallback. This is the subdued text that shows when no value is selected.
* `allow_other` (optional) Off by default, this would add an option called "Add Custom" that would enable typing directly into the dropdown (as if it were an input) — this is the _value_ saved to the database.
    * Alternatively, this could add an input to the end (or beginning) of the list so the user can add a custom option.
* `icon` (optional) Could also be called `left_icon` for consistency. The main question here is what happens to this if the options include icons? In that case, is it just the placeholder icon?

![Screen Shot 2020-04-10 at 11 44 50 AM](https://user-images.githubusercontent.com/522079/79003609-f05cb980-7b20-11ea-9d90-e3e5feaac528.png)

**Comment by benhaynes** [comment]
Option colors and group _naming_ seem to be the most complex things here, so maybe we wait on those. The rest should be pretty straight-forward.
